[package]
name = "etherage"
categories = ["science::robotics", "no-std", "network-programming"]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "An EtherCAT master in pure-Rust very close to the ethercat nature"
keywords = ["no-std", "beckhoff", "ethercat", "igh", "soem", "omron"]
resolver = "2"

[dependencies]
async-io = { version = "1.13.0", optional = true }
futures-lite = { version = "1.12.0", default-features = false }
atomic_enum = "0.2.0"
defmt = "0.3.2"
heapless = "0.7.16"
log = "0.4.17"
num_enum = { version = "^0.6.0", default-features = false }
packed_struct = { version = "0.10.0", default-features = false }
tokio = { version = "1.21.2", features = ["rt-multi-thread", "macros", "sync", "time"] }
bilge = {version="^0.1.4", git="https://github.com/hecatia-elegua/bilge"}

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2.134"
thread-priority = "0.13.1"

[dev-dependencies]
env_logger = "0.10.0"
ctrlc = "3.2.3"
